/**
 * Tuần 1 — Chào hỏi & giới thiệu bản thân (curriculum §7).
 *
 * Trọng tâm phát âm: âm cuối /t/ /d/ /k/ — lỗi nặng nhất của người Việt và là
 * lỗi phá nghĩa nhiều nhất, nên nó đứng đầu bảng ưu tiên ở §9.1.
 *
 * Giáo trình đặt 60 từ cho tuần 1. Đây là phần lõi để chạy được buổi học thật;
 * phần còn lại bổ sung sau theo đúng cấu trúc này.
 */

import type { WeekContent } from "./types";

export const week01: WeekContent = {
  week: 1,
  titleVi: "Chào hỏi & giới thiệu bản thân",
  pronunciationFocusVi: "Âm cuối /t/ /d/ /k/ — đừng nuốt chữ cuối",

  vocabulary: [
    {
      id: "w1-hello",
      week: 1,
      phrase: "Hello, nice to meet you.",
      meaningVi: "Xin chào, rất vui được gặp bạn.",
      situation: "Câu đầu tiên khi gặp người lạ",
      isCoreChunk: true,
    },
    {
      id: "w1-my-name-is",
      week: 1,
      phrase: "My name is Hung.",
      meaningVi: "Tôi tên là Hùng.",
      situation: "Giới thiệu tên mình",
      isCoreChunk: true,
    },
    {
      id: "w1-whats-your-name",
      week: 1,
      phrase: "What's your name?",
      meaningVi: "Bạn tên gì?",
      situation: "Hỏi tên người đối diện",
      isCoreChunk: true,
    },
    {
      id: "w1-im-from",
      week: 1,
      phrase: "I'm from Vietnam.",
      meaningVi: "Tôi đến từ Việt Nam.",
      situation: "Nói mình ở đâu tới",
      isCoreChunk: true,
    },
    {
      id: "w1-where-are-you-from",
      week: 1,
      phrase: "Where are you from?",
      meaningVi: "Bạn từ đâu tới?",
      situation: "Hỏi quê quán",
      isCoreChunk: true,
    },
    {
      id: "w1-i-live-in",
      week: 1,
      phrase: "I live in Ho Chi Minh City.",
      meaningVi: "Tôi sống ở Thành phố Hồ Chí Minh.",
      situation: "Nói nơi đang sống",
      isCoreChunk: false,
    },
    {
      id: "w1-how-are-you",
      week: 1,
      phrase: "How are you?",
      meaningVi: "Bạn khoẻ không?",
      situation: "Chào hỏi hằng ngày",
      isCoreChunk: true,
    },
    {
      id: "w1-im-fine-thanks",
      week: 1,
      phrase: "I'm fine, thanks. And you?",
      meaningVi: "Tôi khoẻ, cảm ơn. Còn bạn?",
      situation: "Trả lời rồi hỏi lại — giữ cho hội thoại không chết",
      isCoreChunk: true,
    },
    {
      id: "w1-nice-to-meet-you-too",
      week: 1,
      phrase: "Nice to meet you too.",
      meaningVi: "Tôi cũng rất vui được gặp bạn.",
      situation: "Đáp lại lời chào làm quen",
      isCoreChunk: true,
    },
    {
      id: "w1-this-is-my-wife",
      week: 1,
      phrase: "This is my wife.",
      meaningVi: "Đây là vợ tôi.",
      situation: "Giới thiệu người đi cùng",
      isCoreChunk: false,
    },
    {
      id: "w1-i-am-retired",
      week: 1,
      phrase: "I'm retired.",
      meaningVi: "Tôi đã nghỉ hưu.",
      situation: "Nói về công việc",
      isCoreChunk: false,
    },
    {
      id: "w1-i-work-at",
      week: 1,
      phrase: "I work at a school.",
      meaningVi: "Tôi làm việc ở một trường học.",
      situation: "Nói mình làm ở đâu",
      isCoreChunk: false,
    },
    {
      id: "w1-sorry-say-again",
      week: 1,
      phrase: "Sorry, could you say that again?",
      meaningVi: "Xin lỗi, bạn nói lại được không?",
      situation: "Câu cứu hộ khi nghe không kịp — học sớm, dùng suốt 6 tháng",
      isCoreChunk: true,
    },
    {
      id: "w1-speak-slowly",
      week: 1,
      phrase: "Could you speak a bit slower, please?",
      meaningVi: "Bạn nói chậm lại một chút được không?",
      situation: "Câu cứu hộ khi người ta nói nhanh quá",
      isCoreChunk: true,
    },
    {
      id: "w1-i-dont-understand",
      week: 1,
      phrase: "Sorry, I don't understand.",
      meaningVi: "Xin lỗi, tôi không hiểu.",
      situation: "Nói thẳng ra còn hơn gật đầu cho qua",
      isCoreChunk: true,
    },
    {
      id: "w1-thank-you",
      week: 1,
      phrase: "Thank you very much.",
      meaningVi: "Cảm ơn bạn nhiều.",
      situation: "Cảm ơn",
      isCoreChunk: true,
    },
    {
      id: "w1-youre-welcome",
      week: 1,
      phrase: "You're welcome.",
      meaningVi: "Không có gì.",
      situation: "Đáp lại lời cảm ơn",
      isCoreChunk: true,
    },
    {
      id: "w1-see-you-later",
      week: 1,
      phrase: "See you later.",
      meaningVi: "Hẹn gặp lại.",
      situation: "Tạm biệt",
      isCoreChunk: true,
    },
    {
      id: "w1-have-a-good-day",
      week: 1,
      phrase: "Have a good day.",
      meaningVi: "Chúc một ngày tốt lành.",
      situation: "Tạm biệt kiểu thân thiện",
      isCoreChunk: true,
    },
    {
      id: "w1-how-old-are-you",
      week: 1,
      phrase: "How old are you?",
      meaningVi: "Bạn bao nhiêu tuổi?",
      situation: "Hỏi tuổi — người Việt hay hỏi, người Tây ít hỏi",
      isCoreChunk: false,
    },
    {
      id: "w1-i-am-sixty",
      week: 1,
      phrase: "I'm sixty years old.",
      meaningVi: "Tôi sáu mươi tuổi.",
      situation: "Nói tuổi mình",
      isCoreChunk: false,
    },
    {
      id: "w1-nice-day",
      week: 1,
      phrase: "It's a nice day today.",
      meaningVi: "Hôm nay trời đẹp.",
      situation: "Bắt chuyện xã giao",
      isCoreChunk: false,
    },
    {
      id: "w1-excuse-me",
      week: 1,
      phrase: "Excuse me.",
      meaningVi: "Xin lỗi cho hỏi / cho tôi đi qua.",
      situation: "Mở lời với người lạ",
      isCoreChunk: true,
    },
    {
      id: "w1-goodbye",
      week: 1,
      phrase: "Goodbye. Take care.",
      meaningVi: "Tạm biệt. Giữ gìn sức khoẻ.",
      situation: "Chào tạm biệt",
      isCoreChunk: false,
    },
  ],

  listening: {
    id: "w1-listen-neighbour",
    week: 1,
    titleVi: "Gặp hàng xóm mới ở thang máy",
    lines: [
      { speaker: "Anna", text: "Oh, hello! Are you my new neighbour?" },
      { speaker: "Hung", text: "Yes, hello. My name is Hung." },
      { speaker: "Anna", text: "Nice to meet you, Hung. I'm Anna. I live in flat nine." },
      { speaker: "Hung", text: "Nice to meet you too. I live in flat eleven." },
      { speaker: "Anna", text: "Welcome! Where are you from?" },
      { speaker: "Hung", text: "I'm from Da Nang. And you?" },
      { speaker: "Anna", text: "I'm from Canada. Have a good day, Hung!" },
    ],
    gist: {
      promptVi: "Hai người này đang làm gì?",
      options: [
        "Làm quen nhau lần đầu",
        "Cãi nhau về tiếng ồn",
        "Hỏi đường ra bến xe",
      ],
      answerIndex: 0,
    },
    detail: [
      {
        promptVi: "Anna ở căn hộ số mấy?",
        options: ["Số 9", "Số 11", "Số 19"],
        answerIndex: 0,
      },
      {
        promptVi: "Ông Hùng quê ở đâu?",
        options: ["Đà Nẵng", "Hà Nội", "Cần Thơ"],
        answerIndex: 0,
      },
      {
        promptVi: "Anna đến từ nước nào?",
        options: ["Canada", "Úc", "Anh"],
        answerIndex: 0,
      },
    ],
    gaps: [
      { before: "Are you my new", answer: "neighbour", after: "?" },
      { before: "Nice to", answer: "meet", after: "you, Hung." },
      { before: "I'm from", answer: "Canada", after: "." },
    ],
  },

  shadowing: [
    {
      id: "w1-sh-1",
      text: "Hello, nice to meet you.",
      focusVi: "Bật rõ chữ 't' cuối trong 'meet'",
    },
    {
      id: "w1-sh-2",
      text: "My name is Hung. What's your name?",
      focusVi: "Đừng nuốt 's' trong \"What's\"",
    },
    {
      id: "w1-sh-3",
      text: "I'm from Vietnam. Where are you from?",
      focusVi: "Lên giọng ở cuối câu hỏi",
    },
    {
      id: "w1-sh-4",
      text: "Sorry, could you say that again?",
      focusVi: "Bật rõ 'd' cuối trong 'could'",
    },
    {
      id: "w1-sh-5",
      text: "Have a good day. See you later.",
      focusVi: "Hai chữ 'good' và 'day' nối vào nhau",
    },
  ],

  roleplay: {
    id: "w1-rp-neighbour",
    week: 1,
    titleVi: "Chào người hàng xóm nước ngoài",
    goalVi: "Nói được tên mình, quê mình, và chào tạm biệt",
    startTurnId: "start",
    turns: [
      {
        id: "start",
        say: "Hello! I'm Anna. What's your name?",
        sayVi: "Xin chào! Tôi là Anna. Bạn tên gì?",
        hints: ["My name is Hung.", "Hello, my name is Hung."],
        branches: [{ keywords: ["name", "i'm", "im", "my"], next: "where-from" }],
        fallbackNext: "repeat-name",
      },
      {
        id: "repeat-name",
        say: "Sorry — what is your name?",
        sayVi: "Xin lỗi — bạn tên là gì?",
        hints: ["My name is Hung."],
        branches: [{ keywords: ["name", "i'm", "im", "my"], next: "where-from" }],
        fallbackNext: "where-from",
      },
      {
        id: "where-from",
        say: "Nice to meet you! Where are you from?",
        sayVi: "Rất vui được gặp bạn! Bạn từ đâu tới?",
        hints: ["I'm from Vietnam.", "I'm from Da Nang."],
        branches: [
          { keywords: ["vietnam", "from", "danang", "da nang", "hanoi", "saigon"], next: "how-are-you" },
        ],
        fallbackNext: "repeat-from",
      },
      {
        id: "repeat-from",
        say: "Sorry, could you say that again? Where are you from?",
        sayVi: "Xin lỗi, bạn nói lại được không? Bạn từ đâu tới?",
        hints: ["I'm from Vietnam."],
        branches: [{ keywords: ["vietnam", "from"], next: "how-are-you" }],
        fallbackNext: "how-are-you",
      },
      {
        id: "how-are-you",
        say: "I'm from Canada. How are you today?",
        sayVi: "Tôi từ Canada. Hôm nay bạn khoẻ không?",
        hints: ["I'm fine, thanks. And you?", "I'm fine, thank you."],
        branches: [{ keywords: ["fine", "good", "well", "ok", "okay", "thanks"], next: "goodbye" }],
        fallbackNext: "goodbye",
      },
      {
        id: "goodbye",
        say: "Good! I have to go now. See you later!",
        sayVi: "Tốt quá! Tôi phải đi rồi. Hẹn gặp lại!",
        hints: ["See you later.", "Goodbye. Have a good day."],
        branches: [{ keywords: ["see", "bye", "goodbye", "later", "day", "care"], next: null }],
        fallbackNext: null,
      },
    ],
  },
};
